return {
    require("plugins.colorscheme"),
    require("plugins.treesitter"),
    require("plugins.todo-comments"),
    require("plugins.nvim-lsp"),
    require("plugins.autopairs"),
    require("plugins.gitsigns"),
    require("plugins.telescope"),
    require("plugins.cmp"),
    require("plugins.nvim-ts-autotag"),
    require("plugins.nvim-hl-colors"),
    require("plugins.illuminate"),
    require("plugins.lualine"),
    require("plugins.oil-nvim"),
}
